apiVersion: v1
kind: Service
metadata:
  name: db2-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: db2
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
      nodePort: 30000