apiVersion: v1
kind: Pod
metadata:
  name: db2-deployment
  namespace: default
  labels:
    app: db2
spec:
  containers:
  - name: db2
    image: icr.io/db2_community/db2
    ports:
    - containerPort: 50000
      protocol: TCP
    env:
    - name: DB2INSTANCE
      value: 'db2inst1'
    - name: ACCEPT_EULA
      value: 'Y'
    - name: DB2INST1_PASSWORD
      value: 'your_password'
    - name: LICENSE
      value: 'accept'
    - name: AUTOCONFIG
      value: 'true'
    - name: SAMPLEDB
      value: 'true'
    securityContext:
      privileged: true